core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('home/',views.HomeView.as_view(), name='index'),
    path('<pk>/detail/', views.ItemDetailView.as_view(),name='detail'),
    path('create-payment-intent',views.createpayment,name='create-payment-intent'),
    path('payment-complete',views.paymentcomplete,name='payment-complete'),
    path('checkout/', views.CheckoutView.as_view(), name='checkout'),
    path('shipping/', views.ShippingView.as_view(), name='shipping'),
    path('account/<pk>/shipping-update/', views.ShippingUpdateView.as_view(),name='shipping-update'),

]

garden_party/urls.py
from django.contrib import admin
from django.urls import path, include
from .import views, settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
#     path('about/', views.AboutPageView.as_view(), name='about'),
#     path('', include('core.urls')),
    path('', include('users.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models
from djstripe.models import Product
from django.conf import settings
from django.shortcuts import reverse
from localflavor.us.models import USStateField,USZipCodeField
# Create your models here.


ADDRESS_CHOICES = (
    ('B', 'Billing'),
    ('S', 'Shipping'),
)

class Address(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE, related_name='address')
    street_address = models.CharField(max_length=100)
    apartment_address = models.CharField(max_length=100, null=True)
    city = models.CharField(max_length=100)
    state = USStateField()
    zip = USZipCodeField()
    address_type = models.CharField(max_length=1, choices=ADDRESS_CHOICES)
    default = models.BooleanField(default=False)

    def __str__(self):
        return f"({self.address_type}) {self.street_address}"

    class Meta:
        verbose_name_plural = 'Addresses'

class MonthlyOrder(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                            on_delete=models.CASCADE, unique_for_month='date')
    date = models.DateField(auto_now_add=True)
    prepared = models.BooleanField(default=False)
    tracking = models.CharField(max_length=100, null=True)

    def __str__(self):
        return f"{self.user}"

core/forms.py
from django import forms
from .models import Address
from localflavor.us.forms import USStateField, USZipCodeField
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit, Layout, Fieldset, Row, Column


class SubscribeForm(forms.ModelForm):
    class Meta:
        model = Address
        fields = [
            'street_address',
            'apartment_address',
            'city',
            'state',
            'zip',
        ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
            Fieldset(
            'Shipping',
            'street_address',
            'apartment_address',
            Row(
                Column('city', css_class='form-group col-md-6 mb-0'),
                Column('state', css_class='form-group col-md-4 mb-0'),
                Column('zip', css_class='form-group col-md-2 mb-0'),
                css_class='form-row'
                ),
            ),
        )
        self.fields['apartment_address'].required = False
        self.helper.form_id = 'shippinng-form'
        self.helper.form_method = 'POST'
        self.helper.disable_csrf = True
        self.helper.form_tag = False

core/views.py
from django.conf import settings
from django.utils.decorators import method_decorator
# from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
# from django.core.exceptions import ObjectDoesNotExist
from django.shortcuts import render, redirect
from djstripe.models import Product, Plan
from .models import Address as A
from users.models import CustomUser
from django.views.decorators.csrf import csrf_exempt
# from django.utils import timezone
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView, View, CreateView, UpdateView
import stripe
import json
import djstripe
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import get_object_or_404
from .forms import SubscribeForm

class HomeView(ListView):
    model = Product
    template_name = 'core/index.html'
    context_object_name = 'products'


class ItemDetailView(DetailView):
    model = Product
    template_name = 'core/item_detail.html'


@csrf_exempt
@login_required
def createpayment(request):

    custom_user = request.user
    stripe.api_key = settings.STRIPE_TEST_SECRET_KEY
    if request.method=="POST":
        data = json.loads(request.body)
        payment_method = data['payment_method']
        payment_method_obj = stripe.PaymentMethod.retrieve(payment_method)
        djstripe.models.PaymentMethod.sync_from_stripe_data(payment_method_obj)

        try:

            # This creates a new Customer and attaches the PaymentMethod in one API call.
            customer = stripe.Customer.create(
	            payment_method=payment_method,
	            email=request.user.email,
	            invoice_settings={
	                'default_payment_method': payment_method
	            })

            djstripe_customer, created = djstripe.models.Customer.sync_from_stripe_data(customer)
            custom_user.customer = djstripe_customer



	        # Subscribe the user to the subscription created
            subscription = stripe.Subscription.create(
	            customer=customer.id,
	            items=[
	                {
	                    "price": data["price_id"],
	                },
	            ],
	            expand=["latest_invoice.payment_intent"]
	        )
            djstripe_subscription = djstripe.models.Subscription.sync_from_stripe_data(subscription)
            custom_user.subscription = djstripe_subscription
            custom_user.save()
            return JsonResponse(subscription)
        except Exception as e:
            return JsonResponse({'error':str(e)},status= 403)
def paymentcomplete(request):
    return render(request, 'core/payment-complete.html')

#
class CheckoutView(LoginRequiredMixin,View):
    def get(self, *args,**kwargs):
        products = Product.objects.all()
        product = Product.objects.filter(name='Classic Garden Party')[0]
        total = Plan.objects.filter(product=product)[0].amount

        context= {
            'products':products,
            'product':product,
            'total':total
        }
        return render(self.request, 'core/checkout.html', context)


class ShippingView(LoginRequiredMixin, View):

    def get(self, *args,**kwargs):
        form = SubscribeForm()

        context= {
            'form':form,
        }
        return render(self.request, 'core/shipping.html', context)

    def post(self, *args, **kwargs):
        form = SubscribeForm(self.request.POST)

        if form.is_valid():
            new_address = form.save(commit=False)
            new_address.user = self.request.user
            new_address.address_type = "S"
            new_address.save()

        return HttpResponseRedirect(reverse('core:checkout'))

class ShippingUpdateView(LoginRequiredMixin, UpdateView):
    model=A
    form_class = SubscribeForm
    template_name = 'core/shipping_update.html'


    def get_success_url(self):
        pk = self.object.pk
        return reverse_lazy('users:account',args=[pk])

templates/core/checkout.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
  <script src="https://js.stripe.com/v3/"></script>

  <div class="container text-center">
    <h1>Subscribe</h1>
    <p class="text-muted "> Step 3 of 3 </p>
    <p class="text-muted ">Enter card details.  Your subscription will start immediately</p>
  </div>
    <div class="col-md-8 my-3 mx-auto">
    	<div class="card mx-5">
    		<div class="card-body">
    			<div class="sr-root">
    				<div class="sr-main">

                  <h4 class="mb-4">Payment</h4>
                  {% for p in products %}
                    <p><strong>Subscription:</strong> {{product.name}}</p>
                    {% for plan in p.plan_set.all %}
                      <p><strong>Total:</strong> ${{total}}</p>
                      <p hidden id="priceId">{{plan.id}}</p>
                    {% endfor %}
                  {% endfor %}

                  <form id="payment-form" >

                      <div id="card-element" class="MyCardElement">
                          <!-- Elements will create input elements here -->
                      </div>
                      <!-- We'll put the error messages in this element -->
                      <div id="card-errors" role="alert"></div>

                      <button id="submit" type="submit">
                          <div class="spinner-border  spinner-border-sm text-light hidden" id="spinner" role="status">
                              <span class="sr-only">Loading...</span>
                          </div>
                          <span id="button-text">Subscribe</span>
                      </button>
                  </form>

    		    </div>
    			</div>
        </div>
    	</div>

</div>


<link rel="stylesheet" href="{% static "StripeElements.css" %}">
<script type="text/javascript" src="{% static 'garden_party/js/script.js' %}"></script>
{% endblock %}

templates/core/index.html
{% extends "base.html" %}
{% load static %}


{% block content %}
    <!--Main layout-->
    <main>
      <div class="container">

        <!--Section: Jumbotron-->
        <section class="card green-gradient wow fadeIn" id="intro">

          <!-- Content -->
          <div class="card-body text-white text-center py-5 px-5 my-5">

            <h1 class="mb-4">
              <strong>Welcome to the Garden Party</strong>
            </h1>
            <p>
              <strong>The best monthly seed delivery</strong>
            </p>
            <p class="mb-4">
              <strong>Anyone can grow their own food, even if you only have a windowsill.
                Start out small with 3 new seeds every month, always delivered to you in season.</strong>
            </p>
            <a href="{% url 'users:signup' %}" class="btn btn-outline-white btn-lg">Sign Up
              <i class="fa fa-envelope-open ml-2"></i>
            </a>

          </div>
          <!-- Content -->
        </section>
        <!--Section: Jumbotron-->

        <!--Section: Cards-->
        <section class="pt-5">

          <!-- Heading & Description -->
          <div class="wow fadeIn">
            <!--Section heading-->
            <h2 class="h1 text-center mb-5">What is The Garden Party?</h2>
            <!--Section description-->
            <p class="text-center">The Garden Party is the best way to start growing your own food!
              </p>
            <p class="text-center mb-5 pb-5">New heirloom seeds every month.
              Always in season. Includes specific growing instructions.
              Grow in any space, be it a windowsill or spacious backyard.</p>


        </div>
          <!-- Heading & Description -->


          <hr class="mb-5">
          <!--Grid row-->
          <div class="row mt-3 mx-auto wow fadeIn">
          {% for product in products  %}
          <!--Grid column-->
            <div class="col-lg-5 col-xl-4 mb-4">
              <div class="view overlay rounded z-depth-1">
                <img src="" alt="" class="img-fluid">
              </div>
            </div>
            <!--Grid column-->

            <!--Grid column-->
            <div class="col-lg-7 col-xl-7 ml-xl-4 mb-4">
              <h3 class="mb-3 font-weight-bold dark-grey-text">
                <strong>{{product.name}}</strong>
              </h3>
              <p class="grey-text">{{product.description}}</p>
              <a href="{% url 'core:detail' pk=product.pk %}" class="btn btn-primary btn-md">Subscribe <i class="fas fa-play ml-2"></i></a>
            </div>
            <!--Grid column-->

          {% endfor %}
          <!--Grid row-->
        </div>

        </section>
        <!--Section: Cards-->

      </div>
    </main>
    <!--Main layout-->
{% endblock content %}

{% block extra_scripts %}


  <script type="text/javascript">
    cardElement.on('change', showCardError);

    function showCardError(event) {
    let displayError = document.getElementById('card-errors');
    if (event.error) {
      displayError.textContent = event.error.message;
    } else {
      displayError.textContent = '';
    }
    }

  </script>
{% endblock extra_scripts %}

templates/core/item_detail.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<!--Main layout-->
<main>
  <div class="container dark-grey-text mt-5">

    <!--Grid row-->
    <div class="row wow fadeIn">
      {{product.image}}

      <!--Grid column-->
      <div class="col-md-6 mb-4">

        <div class="view overlay rounded z-depth-1">
          <img src="{{product.product_image.url}}" class="img-fluid"
            alt="">
        </div>
      </div>
      <!--Grid column-->

      <!--Grid column-->
      <div class="col-md-6 mb-4">

        <!--Content-->
        <div class="p-2">

          <h1>{{product.name}}</h1>
          <p class="lead font-weight-bold">Description</p>

          <p>{{product.description | linebreaks}}</p>
          {% for plan in product.plan_set.all %}
            <p class="lead font-weight-bold">{{plan.human_readable_price}}</p>
          {% endfor %}
          <a class="btn btn-primary" href="{% url 'core:shipping' %}">Subscribe</a>
        </div>
        <!--Content-->
      </div>
      <!--Grid column-->
    </div>
    <!--Grid row-->
<!-- card info-->
</main>
<!--Main layout-->


{% endblock %}

templates/core/payment-complete.html
{% extends "base.html" %}
{% block content %}
<div class="container my-5 pb-5">
  <div class="jumbotron my5-5 pt-5">
    <h1>You've joined the Garden Party!</h1>
    <p>Go to "My Account" to check subscription tracking, history, and other settings."</p>
  </div>
</div>
{% endblock %}

templates/core/shipping.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}

  <div class="container text-center">
    <h1>Subscribe</h1>
    <p class="text-muted "> Step 2 of 3 </p>
    <p class="text-muted ">Enter shipping details. All shipping is free</p>
  </div>
    <div class="col-md-8 my-3 mx-auto">
    	<div class="card mx-5">
    		<div class="card-body">
    			<div class="sr-root">
    				<div class="sr-main">
    					<form class="sr-payment-form" method="POST">
    				    {% csrf_token %}
                  {% crispy form %}
                  <button type="submit" name="button" class="btn" id="submit">Next</button>
              </form>
    		    </div>
    			</div>
        </div>
    	</div>

</div>
</div>

  </div>

{% endblock %}

templates/core/shipping_update.html
{% extends "user_base.html" %}
{% load crispy_forms_tags %}

{% block user_content %}
  <div class="card">
    <div class="card-header">
      Shipping Address Update
    </div>
    <div class="card-body">
      <form method="POST">
        {% csrf_token %}
        {% crispy form %}
        <button type="submit" name="button" class="btn" id="submit">Submit</button>
      </form>

    </div>
  </div>

{% endblock %}