core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('home/',views.HomeView.as_view(), name='index'),
    path('<pk>/detail/', views.ItemDetailView.as_view(),name='detail'),
    path('create-payment-intent',views.createpayment,name='create-payment-intent'),
    path('payment-complete',views.paymentcomplete,name='payment-complete'),
    path('checkout/', views.CheckoutView.as_view(), name='checkout'),
    path('shipping/', views.ShippingView.as_view(), name='shipping'),
    path('account/<pk>/shipping-update/', views.ShippingUpdateView.as_view(),name='shipping-update'),

]

garden_party/urls.py
from django.contrib import admin
from django.urls import path, include
from .import views, settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
#     path('about/', views.AboutPageView.as_view(), name='about'),
#     path('', include('core.urls')),
    path('', include('users.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'users'

urlpatterns = [
#     path('login/', views.LoginView.as_view(), name='login'),
#     path('logout/', auth_views.LogoutView.as_view(), name='logout'),
#     path('signup/', views.SignupView.as_view(), name='signup' ),
    path('', views.LaunchView.as_view(), name='launch'),
    path('launch-success/', views.LaunchSuccessView, name='launch-success'),
#     path('account/<pk>/', views.ProfileView.as_view(), name='account'),
#     path('account/<pk>/profile-update/', views.ProfileUpdate.as_view(),name='profile-update'),
]

templates/about.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div class="col-md-6 mb-4 mx-auto mb-5 pb-5">
  <div class="view overlay rounded">
    <img src="{% static "garden_party/img/GP-logo-big.png" %}" class="img-fluid"
      alt="">
  </div>
</div>




{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
  <script src="https://use.fontawesome.com/4629e5d856.js"></script>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Garden Party</title>


    <link rel="stylesheet" href="{% static "StripeElements.css" %}">

    {% block extra_head %}

    {% endblock %}
    <!-- Font Awesome -->
    <!-- Bootstrap core CSS -->
    <link href="{% static "garden_party/css/bootstrap.min.css" %}" rel="stylesheet">
    <!-- Material Design Bootstrap -->
    <link href="{% static "garden_party/css/mdb.min.css" %}" rel="stylesheet">
    <!-- Your custom styles (optional) -->
    <link href="{% static "garden_party/css/style.min.css" %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static "master.css" %}">

</head>

<body>

    <!--Main Navigation-->
    <header>

        <!-- Navbar -->
        <nav class="navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar">
            <div class="container">

                <!-- Brand -->
                <a class="navbar-brand waves-effect" href="{% url 'users:launch' %}">
                  <img src="{% static "garden_party/img/GP-logo.png" %}" alt="">
                </a>

                <!-- Collapse -->
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <!-- Links -->
                <div class="collapse navbar-collapse" id="navbarSupportedContent">

                    <!-- Left -->
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item">
                            <a class="nav-link waves-effect" href="{% url 'users:launch' %}">Home</a>
                        </li>
                        <!-- <li class="nav-item">
                            <a class="nav-link waves-effect" href="{% url 'about' %}" target="_blank">About</a>
                        </li> -->
                    </ul>
                    <ul class="navbar-nav mr-auto">
                      <li class="nav-item">
                        <h4>The Garden Party: Coming Soon!</h4>
                      </li>
                    </ul>
                    <!-- Right -->
                    <ul class="navbar-nav nav-flex-icons">
                        <li class="nav-item">
                            <a href="#" class="nav-link waves-effect" target="_blank">
                                <i class="fab fa-facebook-f"></i>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="#" class="nav-link waves-effect" target="_blank">
                                <i class="fab fa-instagram"></i>
                            </a>
                        </li>

                          {% if user.is_authenticated %}
                          <li class="nav-item dropdown">
                            <a href="#" class="nav-link dropdown-toggle" id='navbarDropdown' role="button"data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                              My Account
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                              <a href="{% url 'users:account' pk=request.user.pk %}" class="dropdown-item waves-effect">
                                <i class="fa fa-user mr-3"></i>Profile</a>
                              <a href="#" class="dropdown-item waves-effect">
                                <i class="fa fa-envelope-open mr-3"></i>Subscription
                              </a>
                              <a href="#" class="dropdown-item waves-effect">
                                <i class="fa fa-table mr-3"></i>History</a>
                            </div>

                          </li>

                          <li class="nav-item">
                            <a href="{% url 'users:logout' %}" class="nav-link waves-effect">Logout</a>
                          </li>
                          {% else %}
                          <!-- <li class="nav-item">
                            <a href="{% url 'users:login' %}" class="nav-link border border-light rounded waves-effect">Login</a>
                          </li> -->
                          {% endif %}

                    </ul>

                </div>

            </div>
        </nav>
        <!-- Navbar -->

    </header>
    <!--Main Navigation-->
    <main class="my-5 py-5">
      <div class="">
        {% block content %}

        {% endblock %}
      </div>
    </main>


    <!--Footer-->

    <!-- SCRIPTS -->
    <!-- JQuery -->
    <script type="text/javascript" src="{% static "garden_party/js/jquery-3.4.1.min.js" %}"></script>
    <!-- Bootstrap tooltips -->
    <script type="text/javascript" src="{% static "garden_party/js/popper.min.js" %}"></script>
    <!-- Bootstrap core JavaScript -->
    <script type="text/javascript" src="{% static "garden_party/js/bootstrap.min.js" %}"></script>
    <!-- MDB core JavaScript -->
    <script type="text/javascript" src="{% static "garden_party/js/mdb.min.js" %}"></script>
    <!-- Initializations -->
    <script type="text/javascript">
        // Animations initialization
        new WOW().init();
    </script>



</body>

</html>

templates/launch.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
    <!--Main layout-->
    <main>
      <div class="container">

        <!--Section: Jumbotron-->
        <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
              <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
              <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
              <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
            </ol>
            <div class="carousel-inner">
              <div class="carousel-item active">
                <img class="d-block w-75 mx-auto" src="{% static "garden_party/img/SeedsInSpoons2.png" %}" alt="First slide">
              </div>
              <div class="carousel-item">
                <img class="d-block w-75 mx-auto" src="{% static "garden_party/img/PotsInSmallSpace.png" %}" alt="Second slide">
              </div>
              <div class="carousel-item">
                <img class="d-block w-75 mx-auto" src="{% static "garden_party/img/TomatoBasilSoup2.png" %}" alt="Third slide">
              </div>
            </div>
            <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
              <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
              <span class="carousel-control-next-icon" aria-hidden="true"></span>
              <span class="sr-only">Next</span>
            </a>
        </div>
        <!--Section: Jumbotron-->

        <!--Section: Cards-->
        <section class="pt-5">

          <!-- Heading & Description -->
          <div class="wow fadeIn">
            <!--Section heading-->
            <h2 class="h1 text-center mb-5">What is The Garden Party?</h2>
            <!--Section description-->
            <p class="text-center">The Garden Party is a brand new gardening subscription startup!
              </p>
            <p class="text-center mb-5 pb-5">Subscribe and receive new, edible seeds every month.
              Each month has a different recipe theme. Grow the seeds, and use in the recipe! Includes specific growing instructions.
              Specifically designed for small spaces, anyone can grow their own food, even on a windowsill.</p>


        </div>
          <!-- Heading & Description -->


          <hr class="mb-5">
          <div class="container text-center">
            <h1>Want to be notified on Launch Day?</h1>
            <p class="text-muted ">Enter your email below to join the Garden Party Launch List!</p>
          </div>
            <div class="col-md-8 my-3 mx-auto">
            	<div class="card mx-5">
            		<div class="card-body">
            					<form method="POST">
            				      {% csrf_token %}
                          {{form|crispy}}
                          <button type="submit" name="button" class="btn" id="submit">Sign Up</button>
                      </form>
                </div>
            	</div>

        </div>
        </div>

          </div>

          <!--Grid row-->

        </section>
        <!--Section: Cards-->

      </div>
    </main>
    <!--Main layout-->
{% endblock content %}

templates/user_base.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<div class="mb-5 mt-2 pb-5">

        <div class="col-md-7 mx-auto">

          {% block user_content %}

          {% endblock user_content %}

        </div>

    </div>
{% endblock content %}