core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('home/',views.HomeView.as_view(), name='index'),
    path('<pk>/detail/', views.ItemDetailView.as_view(),name='detail'),
    path('create-payment-intent',views.createpayment,name='create-payment-intent'),
    path('payment-complete',views.paymentcomplete,name='payment-complete'),
    path('checkout/', views.CheckoutView.as_view(), name='checkout'),
    path('shipping/', views.ShippingView.as_view(), name='shipping'),
    path('account/<pk>/shipping-update/', views.ShippingUpdateView.as_view(),name='shipping-update'),

]

garden_party/urls.py
from django.contrib import admin
from django.urls import path, include
from .import views, settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
#     path('about/', views.AboutPageView.as_view(), name='about'),
#     path('', include('core.urls')),
    path('', include('users.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'users'

urlpatterns = [
#     path('login/', views.LoginView.as_view(), name='login'),
#     path('logout/', auth_views.LogoutView.as_view(), name='logout'),
#     path('signup/', views.SignupView.as_view(), name='signup' ),
    path('', views.LaunchView.as_view(), name='launch'),
    path('launch-success/', views.LaunchSuccessView, name='launch-success'),
#     path('account/<pk>/', views.ProfileView.as_view(), name='account'),
#     path('account/<pk>/profile-update/', views.ProfileUpdate.as_view(),name='profile-update'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from djstripe.models import Subscription, Customer
from django.utils.functional import cached_property
from djstripe.utils import subscriber_has_active_subscription
from django.utils.translation import gettext_lazy as _

# Create your models here.
class CustomUser(models.Model):
    user = models.CharField(max_length=50, unique=True)
#     email = models.EmailField(_('email address'), unique=True)
#     customer = models.ForeignKey(
#         Customer, null=True, blank=True, on_delete=models.SET_NULL,
#         help_text="The user's Stripe Customer object, if it exists"
#     )
#     subscription = models.ForeignKey(
#         Subscription, null=True, blank=True, on_delete=models.SET_NULL,
#         help_text="The user's Stripe Subscription object, if it exists"
#     )

#     @cached_property
#     def has_active_subscription(self):
#         """Checks if a user has an active subscription."""
#         return subscriber_has_active_subscription(self)

#     def __str__(self):
#         return (self.email)

#     def save(self, *args, **kwargs):
#         if not self.username:
#             self.username = self.email
#         super(CustomUser,self).save(*args,**kwargs)

class LaunchSignUp(models.Model):
    email = models.EmailField(_('email address'), unique=True)

    def __str__(self):
        return (self.email)

users/forms.py
from django import forms
from django.contrib.auth import get_user_model
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit, Layout, Fieldset, Row, Column
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm


class LoginForm(AuthenticationForm):
    username = forms.CharField(label='Email')

    def __init__(self,*args,**kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = False

class SignUpForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = (
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2',
        )

    def __init__(self,*args,**kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
            Fieldset(
            'Account Information',
            Row(
                Column('first_name', css_class='form-group col-md-6'),
                Column('last_name', css_class='form-group col-md-6'),
            ),
            'email',
            'password1',
            'password2',
            )
        )
        self.helper.form_tag = False

users/views.py
from django.shortcuts import render
# from django.http import HttpResponseRedirect

from django.urls import reverse_lazy
from django.contrib.auth import login, authenticate
from .forms import SignUpForm, LoginForm
from django.views.generic import ListView, DetailView, View, FormView, UpdateView, CreateView
from django.contrib.auth import views as auth_views
from djstripe.models import PaymentMethod

from .models import CustomUser, LaunchSignUp
from core.models import Address

# Create your views here.
class LoginView(auth_views.LoginView):
    form_class = LoginForm
    template_name = 'registration/login.html'

class ProfileView(View):

    def get(self, *args, **kwargs):
        user = self.request.user
        address = Address.objects.filter(user=user)[0]
        last4 = self.request.user.customer.default_payment_method.card['last4']


        context = {
            'user':user,
            'last4': last4,
            'address_pk': address.pk,
            'street_address':address.street_address,
            'apt_address':address.apartment_address,
            'city':address.city,
            'state':address.state,
            'zip':address.zip,
        }
        return render(self.request, 'users/user_detail.html', context)



class ProfileUpdate(UpdateView):
    model = CustomUser
    template_name = 'users/user_update.html'
    fields = ['first_name', 'last_name', 'email',]

    def get_success_url(self):
        pk = self.object.pk
        return reverse_lazy('users:account',args=[pk])

class SignupView(CreateView):
    form_class = SignUpForm
    template_name = 'users/signup.html'

    def get_success_url(self):
        return reverse_lazy('core:shipping')

    def form_valid(self, form):
        valid = super(SignupView, self).form_valid(form)
        username, password = form.cleaned_data.get('email'), form.cleaned_data.get('password1')
        user = authenticate(username=username,
                            password=password)
        login(self.request, user)
        return valid

class LaunchView(CreateView):
    model = LaunchSignUp
    template_name = 'launch.html'
    fields = ['email']

    def get_success_url(self):
        return reverse_lazy('users:launch-success')

def LaunchSuccessView(request):
    return render(request, 'users/launch_success.html')

templates/users/launch_success.html
{% extends "base.html" %}
{% block content %}
<div class="container my-5 pb-5">
  <div class="jumbotron my5-5 pt-5">
    <h1>You've joined the Garden Party Launch List!</h1>
    <p>We'll notify you on Launch Day.</p>
  </div>
</div>
{% endblock %}

templates/users/signup.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}

<div class="container text-center">
  <h1>Subscribe</h1>
  <p class="text-muted "> Step 1 of 3: Enter account details to easily check on your subscriptions and change preferences.</p>
</div>
  <div class="col-md-8 my-3 mx-auto">
    <div class="card mx-5">
      <div class="card-body">
        <div class="sr-root">
          <div class="sr-main">
            <form class="sr-payment-form" method="POST">
              {% csrf_token %}
                {% crispy form %}
                <button type="submit" name="button" class="btn" id="submit">Next</button>
            </form>
          </div>
        </div>
      </div>
    </div>

</div>
</div>

</div>



{% endblock %}

templates/users/user_detail.html
{% extends "user_base.html" %}
{% block user_content %}

<div class="card">
  <div class="card-header">
    Hello, {{user.first_name}}
  </div>
  <div class="card-body  mb-2">
    <h5 class="card-title">Account Info</h5>
    <p class="card-text">Name: <span class="float-right">
      {{user.first_name}} {{user.last_name}}
      <a href="{% url 'users:profile-update' pk=user.pk %}"><i class="fa fa-pencil"></i></a>
    </span>
    </p>
    <p class="card-text">Email: <span class="float-right">{{user.email}}
      <a href="{% url 'users:profile-update' pk=user.pk %}"><i class="fa fa-pencil"></i></a>
    </span></p>
    <p class="card-text">Shipping Address:
      <span class="float-right">{{street_address}}{% if apt_address %}, {{apt_address}}{% endif %} <br>
        {{city}}, {{state}} {{zip}}
        <a href="{% url 'core:shipping-update' pk=address_pk %}"><i class="fa fa-pencil"></i></a>
      </span>
    </p>
    <br>
    <p class="card-text">Payment Method: <span class="float-right">**** **** **** {{last4}}</span></p>
  </div>
</div>
<!-- Heading -->


{% endblock %}

templates/users/user_update.html
{% extends "user_base.html" %}
{% load crispy_forms_tags %}

{% block user_content %}
  <div class="card">
    <div class="card-header">
      Account Info Update
    </div>
    <div class="card-body">
      <form method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" name="button" class="btn" id="submit">Submit</button>
      </form>

    </div>
  </div>

{% endblock %}